version: "3.8" 

services: 
  create-service:
    build:
      context: ./create  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  list-service:
    build: 
      context: ./list  
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  update-service: 
    build: 
      context: ./update  
      dockerfile: Dockerfile 
    ports:
      - "3003:3003" 

  remove-service:
    build: 
      context: ./remove  
      dockerfile: Dockerfile 
    ports:
      - "3004:3004" 

