### atualiza user por id
PUT http://localhost:3003/users/6746351507db4179276e7fe8
Content-Type: application/json

{
  "username": "COTUCA_Aluno05",
  "password": "aluno05cotuca"
}


### lista usuarios
GET http://localhost:3002/users


### criação de users
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "COTUCA_Aluno16",
  "password": "aluno16cotuca"
}

### get test
GET http://localhost:3001/

### Delete user por id
DELETE http://localhost:3004/users/67493bfd7f158bbdde0abe71